#!/usr/bin/env python3
"""
Generate tools_manifest.yaml by connecting to the Stigix MCP server,
discovering all tools via list_tools(), and writing a manifest skeleton.

Usage:
    cd mcp-server
    .venv/bin/python tests/generate_manifest.py
"""

import asyncio
import os
import sys
import yaml

# Ensure tests/ is importable
sys.path.insert(0, os.path.dirname(__file__))
from mcp_harness import MCPTestHarness, _generate_args_from_schema

# Known tool categorizations (manually curated based on server.py review)
WRITE_TOOLS = {
    "run_test", "stop_test", "set_traffic_status", "set_traffic_rate",
    "set_voice_status", "set_traffic_client_count",
    "run_vyos_scenario", "set_vyos_scenario_status", "vyos_bulk_reset",
    "vyos_execute_action",
    "run_security_probe", "run_security_url_batch", "run_security_dns_batch",
    "run_full_security_audit", "run_eicar_test",
    "run_dem_probes_now", "add_dem_probe", "remove_dem_probe", "update_dem_probe",
    "add_fabric_target", "remove_fabric_target", "set_fabric_target_enabled",
    "import_app_config", "clone_node_config",
    "create_custom_tcp_app", "add_tcp_app_peer", "delete_custom_tcp_app",
    "start_tcp_app_listener", "stop_tcp_app_listener",
    "start_tcp_app_workload", "stop_tcp_app_workload",
    "test_tcp_app_handshake", "reset_tcp_app_metrics",
    "set_controller_leader", "set_provisioning_mode",
}

DESTRUCTIVE_TOOLS = {
    "publish_configuration_bundle", "rollback_configuration_bundle",
    "purge_stale_leader_state",
}

LONG_TIMEOUT_TOOLS = {
    "run_dem_probes_now", "run_full_security_audit", "run_test",
    "run_system_diagnostics", "generate_report",
    "run_security_url_batch", "run_security_dns_batch",
    "vyos_bulk_reset", "clone_node_config",
}

MEDIUM_TIMEOUT_TOOLS = {
    "stop_test", "run_security_probe", "run_eicar_test",
    "run_vyos_scenario", "vyos_execute_action",
    "run_path_trace", "publish_configuration_bundle",
    "rollback_configuration_bundle", "purge_stale_leader_state",
    "create_custom_tcp_app", "start_tcp_app_workload",
    "test_tcp_app_handshake", "get_prisma_flows",
}


def categorize(name: str) -> str:
    if name in DESTRUCTIVE_TOOLS:
        return "destructive"
    if name in WRITE_TOOLS:
        return "write"
    return "read"


def timeout_class(name: str) -> str:
    if name in LONG_TIMEOUT_TOOLS:
        return "long"
    if name in MEDIUM_TIMEOUT_TOOLS:
        return "medium"
    return "fast"


async def main():
    # Start mock nodes in background threads (needed for discovery)
    import threading
    import time
    import httpx

    # Use a simple mock that only serves /api/targets and /admin/mode
    from mock_stigix_node import create_app
    import uvicorn

    MOCK_PORT = 19080
    CANARY_PORT = 19081

    def run_mock(port, node_id):
        app = create_app(port=port, node_id=node_id)
        config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="error")
        server = uvicorn.Server(config)
        server.run()

    t1 = threading.Thread(target=run_mock, args=(MOCK_PORT, "mock-primary"), daemon=True)
    t2 = threading.Thread(target=run_mock, args=(CANARY_PORT, "mock-canary"), daemon=True)
    t1.start()
    t2.start()

    # Wait for mocks to be ready
    for port in [MOCK_PORT, CANARY_PORT]:
        for _ in range(30):
            try:
                r = httpx.get(f"http://127.0.0.1:{port}/admin/mode", timeout=1.0)
                if r.status_code == 200:
                    break
            except Exception:
                pass
            time.sleep(0.2)

    # Connect harness
    harness = MCPTestHarness(mock_port=MOCK_PORT, canary_port=CANARY_PORT)
    try:
        tools = await harness.connect()
    except Exception as e:
        print(f"ERROR: Failed to connect to MCP server: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Discovered {len(tools)} tools.", file=sys.stderr)

    # Build manifest
    manifest = {"tools": {}}
    for tool in sorted(tools, key=lambda t: t.name):
        schema = tool.inputSchema if hasattr(tool, "inputSchema") else {}
        cat = categorize(tool.name)
        tc = timeout_class(tool.name)

        entry = {
            "category": cat,
            "timeout_class": tc,
            "size_budget_kb": 50 if tc == "long" else 20,
        }
        if cat == "destructive":
            entry["safe_defaults"] = True

        manifest["tools"][tool.name] = entry

    # Write manifest
    manifest_path = os.path.join(os.path.dirname(__file__), "tools_manifest.yaml")
    with open(manifest_path, "w") as f:
        f.write("# tools_manifest.yaml — Stigix MCP Tool Catalog\n")
        f.write("# Auto-generated by generate_manifest.py, manually curated.\n")
        f.write("# category: read | write | destructive\n")
        f.write("# timeout_class: fast (<10s) | medium (<60s) | long (<120s)\n")
        f.write("# size_budget_kb: max response size in KB\n\n")
        yaml.dump(manifest, f, default_flow_style=False, sort_keys=True)

    print(f"Written {len(manifest['tools'])} tools to {manifest_path}", file=sys.stderr)

    await harness.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
